src/main/java/br/com/maralto/webappbiblioteca/bean/AutorBean.java
package br.com.maralto.webappbiblioteca.bean;

import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import br.com.maralto.webappbiblioteca.model.Autor;
import br.com.maralto.webappbiblioteca.service.AutorService;

@Controller
@Scope("session")
public class AutorBean {

	private Autor autor;
	private Autor autorSelected;
	private List<Autor> autoresList;

	@Autowired
	AutorService autorService;
	

	@PostConstruct
	private void init() {

		autor = new Autor();
		findAll();
	}

	public void findAll() {

		autoresList = autorService.findAll();

	}
	
	public void prepareSave() {
		this.autor = new Autor();
	}

	public void prepareUpdate(Autor autor) {
		this.autor = autor;
	}
	
	public void save() {

		autorService.save(autor);

		findAll();

		reset();

	}

	private void reset() {
		autor = new Autor();
		autorSelected = new Autor();

	}

	public Autor getAutor() {
		return autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public Autor getAutorSelected() {
		return autorSelected;
	}

	public void setAutorSelected(Autor autorSelected) {
		this.autorSelected = autorSelected;
	}

	public List<Autor> getAutoresList() {
		return autoresList;
	}

	public void setAutoresList(List<Autor> autoresList) {
		this.autoresList = autoresList;
	}

}

src/main/java/br/com/maralto/webappbiblioteca/bean/EmprestimoBean.java
package br.com.maralto.webappbiblioteca.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import br.com.maralto.webappbiblioteca.model.Autor;
import br.com.maralto.webappbiblioteca.model.ControleEmprestimo;
import br.com.maralto.webappbiblioteca.model.Emprestimo;
import br.com.maralto.webappbiblioteca.model.Livro;
import br.com.maralto.webappbiblioteca.model.Pessoa;
import br.com.maralto.webappbiblioteca.model.Usuario;
import br.com.maralto.webappbiblioteca.service.AutorService;
import br.com.maralto.webappbiblioteca.service.ControleEmprestimoService;
import br.com.maralto.webappbiblioteca.service.EmprestimoService;
import br.com.maralto.webappbiblioteca.service.LivroService;
import br.com.maralto.webappbiblioteca.service.PessoaService;
import br.com.maralto.webappbiblioteca.service.UsuarioService;
import br.com.maralto.webappbiblioteca.util.ConvertDate;
import br.com.maralto.webappbiblioteca.util.jsf.FacesMessageUtils;
import br.com.maralto.webappbiblioteca.util.security.AuthenticationFacade;

@Controller
@Scope("session")
public class EmprestimoBean {

	private Livro livro;
	private Usuario usuario;
	private String filtroCpf;
	private String filtroNome;
	private String filtroAutor;
	private String filtroTitulo;
	private Emprestimo emprestimo;
	private List<Livro> livrosList;
	private List<Pessoa> pessoasList;
	private List<Emprestimo> emprestimosList;
	private ControleEmprestimo controleEmprestimo;
	private List<ControleEmprestimo> controleEmprestimoList;
	
	@Autowired
	private LivroService livroService;

	@Autowired
	private AutorService autorService;
	
	@Autowired
	private PessoaService pessoaService;
	
	@Autowired
	private UsuarioService usuarioService;
		
	@Autowired
	private EmprestimoService emprestimoService;
	
	@Autowired
	private FacesMessageUtils facesMessageUtils;
	
	@Autowired
	private AuthenticationFacade authenticationFacade;
	
	@Autowired
	private ControleEmprestimoService controleEmprestimoService;
	
	@PostConstruct
	private void init() {
		this.filtroCpf = "";
		this.filtroNome = "";
		this.emprestimo = new Emprestimo();
		this.livrosList = new ArrayList<Livro>();
		this.emprestimosList = new ArrayList<Emprestimo>();
		this.controleEmprestimoList = new ArrayList<ControleEmprestimo>();
		this.usuario = usuarioService.findByLogin(authenticationFacade.getAuthentication().getName());
	}

	public void findAll() {
		
		emprestimosList = emprestimoService.findAll();
	}

	public void buscaPessoa() {

		if (!this.filtroCpf.equals("") && !this.filtroCpf.equals("")) {
			pessoasList = pessoaService.findByCpf(this.filtroCpf);
		} else {
			pessoasList = pessoaService.findByNome(this.filtroNome);
		}
		this.filtroCpf = "";
		this.filtroNome = "";
	}

	public void buscaLivros() {

		if (!this.filtroTitulo.equals("") || !this.filtroAutor.equals("")) {

			if (!this.filtroTitulo.equals("")) {
				this.livrosList = livroService.findLivrosByTituloAndStatus(this.filtroTitulo);
			} else {
				List<Autor> autores = autorService.findByNomeContains(this.filtroAutor);
				for (Autor a : autores) {

					for (Livro l : a.getLivrosList()) {
							this.livrosList.add(l);
					}
				}
			}

		}
		
		this.filtroTitulo = "";
		this.filtroAutor = "";
	}

	public void addPessoa(Pessoa pessoa) {

		this.emprestimo.setPessoa(pessoa);

	}
	
	public void prepareControleEmprestimo() {
		
		this.filtroCpf = "";
		this.filtroNome = "";
		this.emprestimo= new Emprestimo();
		this.emprestimo.setDataEmprestimo(new Date());
		this.emprestimo.setDataDevolucao(ConvertDate.addMesAData(new Date()));
		this.livrosList = new ArrayList<Livro>();
		this.pessoasList = new ArrayList<Pessoa>();
		this.controleEmprestimo = new ControleEmprestimo();
		this.controleEmprestimo.setSituacao("DISPONIVEL");
	}

	public void addLivro(Livro livro) {
		
		boolean encontrado = false;
		this.controleEmprestimo = new ControleEmprestimo();
		

		for (ControleEmprestimo c : this.emprestimo.getControleEmprestimoList()) {
			if (c.getLivro().getId() == livro.getId()) {
				encontrado = true;
			}
		}

		if (!encontrado) {
			this.controleEmprestimo.setLivro(livro);
			this.controleEmprestimo.setDataEmprestimo(new Date());
			this.controleEmprestimo.setEmprestimo(this.emprestimo);
			this.controleEmprestimo.setUsuario(this.usuario);
			this.controleEmprestimo.setSituacao("EMPRESTADO");
			this.emprestimo.getControleEmprestimoList().add(controleEmprestimo);
		}
		
		livro = new Livro();
		this.filtroTitulo = "";
		this.filtroAutor = "";
	}

	public void removeControleEmprestimo(ControleEmprestimo controleEmprestimo) {
		this.emprestimo.getControleEmprestimoList().remove(controleEmprestimo);
	}

	public boolean validaDadosEmprestimo() {
		

		if (this.emprestimo.getPessoa() != null && this.emprestimo.getPessoa().getCpf() != null && !this.emprestimo.getPessoa().getCpf().equals("")) {
			if (!this.emprestimo.getControleEmprestimoList().isEmpty()) {
				return true;
			} else {
				facesMessageUtils.addErrorMessage("Nenhum livro foi selecionado para o empréstimo");
				return false;
			}
		} else {
			facesMessageUtils.addErrorMessage("O Campo CPF é Obrigatório");
			return false;
		}

	}
	
	public void  saveEmprestimo() {
		
		if(validaDadosEmprestimo()) {
			emprestimoService.save(this.emprestimo);
			reset();
		}
	}
	
	public void toogleIsItemDevolucaoList(ControleEmprestimo controleEmprestimo) {

		if (controleEmprestimo.isItemDevolucaoList()) {
			controleEmprestimo.setItemDevolucaoList(false);
		} else {
			controleEmprestimo.setItemDevolucaoList(true);
		}
	}
	
	private boolean validaDadosfinalizacaoEmprestimo() {
		
		boolean isListaDesmarcada = true;
		
		for (ControleEmprestimo controleEmprestimo : this.emprestimo.getControleEmprestimoList()) {
			if(controleEmprestimo.isItemDevolucaoList()) {
				isListaDesmarcada = false;
			}
		}
		
		if(isListaDesmarcada) {
			facesMessageUtils.addErrorMessage("Para Finalizar um empréstimo você deve selecionar no mínimo um livro");
			return false;
		}
		
		return true;
	}
	
	public void finalizarEmprestimo() {
		
		if(validaDadosfinalizacaoEmprestimo())
		emprestimoService.save(this.emprestimo);
		
	}
	
	public void showEmprestimo(Emprestimo e) {
		
		List<ControleEmprestimo> controleEmprestimoBusca = new ArrayList<ControleEmprestimo>();
		
		controleEmprestimoBusca = controleEmprestimoService.findByEmprestimoAtivo(e);
		
		this.emprestimo.setId(e.getId());
		this.emprestimo.setControleEmprestimoList(controleEmprestimoBusca);
		this.emprestimo.setPessoa(e.getPessoa());
		this.emprestimo.setObservacao(e.getObservacao());
		this.emprestimo.setDataEmprestimo(e.getDataEmprestimo());
		this.emprestimo.setDataDevolucao(e.getDataDevolucao());
	}
	
	private void reset() {
		this.emprestimo = new Emprestimo();
		this.controleEmprestimo = new ControleEmprestimo();
	}

	public List<Pessoa> getPessoasList() {
		return pessoasList;
	}

	public void setPessoasList(List<Pessoa> pessoasList) {
		this.pessoasList = pessoasList;
	}

	public String getFiltroNome() {
		return filtroNome;
	}

	public void setFiltroNome(String filtroNome) {
		this.filtroNome = filtroNome;
	}

	public String getFiltroCpf() {
		return filtroCpf;
	}

	public void setFiltroCpf(String filtroCpf) {
		this.filtroCpf = filtroCpf;
	}

	public String getFiltroTitulo() {
		return filtroTitulo;
	}

	public void setFiltroTitulo(String filtroTitulo) {
		this.filtroTitulo = filtroTitulo;
	}

	public String getFiltroAutor() {
		return filtroAutor;
	}

	public void setFiltroAutor(String filtroAutor) {
		this.filtroAutor = filtroAutor;
	}

	public List<Livro> getLivrosList() {
		return livrosList;
	}

	public void setLivrosList(List<Livro> livrosList) {
		this.livrosList = livrosList;
	}

	public Livro getLivro() {
		return livro;
	}

	public void setLivro(Livro livro) {
		this.livro = livro;
	}

	public Emprestimo getEmprestimo() {
		return emprestimo;
	}

	public void setEmprestimo(Emprestimo emprestimo) {
		this.emprestimo = emprestimo;
	}

	public List<Emprestimo> getEmprestimosList() {
		findAll();
		return emprestimosList;
	}

	public void setEmprestimosList(List<Emprestimo> emprestimosList) {
		this.emprestimosList = emprestimosList;
	}

	public ControleEmprestimo getControleEmprestimo() {
		return controleEmprestimo;
	}

	public void setControleEmprestimo(ControleEmprestimo controleEmprestimo) {
		this.controleEmprestimo = controleEmprestimo;
	}

	public List<ControleEmprestimo> getControleEmprestimoList() {
		return controleEmprestimoList;
	}

	public void setControleEmprestimoList(List<ControleEmprestimo> controleEmprestimoList) {
		this.controleEmprestimoList = controleEmprestimoList;
	}

}

src/main/java/br/com/maralto/webappbiblioteca/model/Autor.java
package br.com.maralto.webappbiblioteca.model;

import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import br.com.maralto.webappbiblioteca.util.model.PersistentEntity;
@Entity
@Table(name = "AUTORES")
@AttributeOverride(name = "id", column = @Column(name = "AUT_ID"))
public class Autor extends PersistentEntity {

	private static final long serialVersionUID = 1L;
	@Column(name="AUT_NOME")
	private String nome;

	@ManyToMany(mappedBy = "autoresList", fetch = FetchType.EAGER)
	List<Livro> livrosList;
	
	public Autor() {
	}

	public Autor(String nome) {
		this.nome = nome;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<Livro> getLivrosList() {
		return livrosList;
	}

	public void setLivrosList(List<Livro> livrosList) {
		this.livrosList = livrosList;
	}
	
}

src/main/java/br/com/maralto/webappbiblioteca/model/Pessoa.java
package br.com.maralto.webappbiblioteca.model;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import br.com.maralto.webappbiblioteca.util.ConvertDate;
import br.com.maralto.webappbiblioteca.util.model.PersistentEntity;


@Entity
@Table(name = "PESSOAS")
@AttributeOverride(name = "id", column = @Column(name = "PES_ID"))
public class Pessoa  extends PersistentEntity {

	private static final long serialVersionUID = 1L;
	@Column(name = "PES_NOME")
	private String nome;
	@Column(name = "PES_CPF")
	private String cpf;
	@Column(name = "PES_EMAIL")
	private String email;
	@Column(name = "PES_DATA_NASCIMENTO")
	@Temporal(TemporalType.DATE )
	private Date dataNascimento;
	@Column(name = "PES_DATA_CADASTRO")
	@Temporal(TemporalType.DATE)
	private Date dataCadastro;
	@Column(name = "PES_CONTATO1")
	private String contato1;
	@Column(name = "PES_CONTATO2")
	private String contato2;
	@Column(name = "PES_LOGRADOURO")
	private String logradouro;
	@Column(name = "PES_NUMERO")
	private String numero;
	@Column(name = "PES_COMPLEMENTO")
	private String complemento;
	@Column(name = "PES_BAIRRO")
	private String bairro;
	@Column(name = "PES_CEP")
	private String cep;
	@Column(name = "PES_CIDADE")
	private String cidade;
	@Column(name = "PES_UF")
	private String uf;

		
	public Pessoa() {
	}
		
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getDataCadastro() {
		return dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}
	
	public String getDataNascimentoFormatado() {
		return ConvertDate.DateToString(this.dataNascimento);
	}

	public void setDataNascimento(Date dataNascimento) {
		
		this.dataNascimento = dataNascimento;
	}

	public String getContato1() {
		return contato1;
	}

	public void setContato1(String contato1) {
		this.contato1 = contato1;
	}

	public String getContato2() {
		return contato2;
	}

	public void setContato2(String contato2) {
		this.contato2 = contato2;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getUf() {
		return uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/br/com/maralto/webappbiblioteca/util/model/SampleEntity.java
package br.com.maralto.webappbiblioteca.util.model;

public interface SampleEntity {
	Long getId();
	void setId(Long id);
}

src/main/java/br/com/maralto/webappbiblioteca/util/security/SecurityController.java
package br.com.maralto.webappbiblioteca.util.security;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;

import br.com.maralto.webappbiblioteca.model.Usuario;
import br.com.maralto.webappbiblioteca.service.UsuarioService;
import br.com.maralto.webappbiblioteca.util.jsf.FacesMessageUtils;

@Controller
@Scope("session")
public class SecurityController {

	private Usuario usuario;
	private String senha;
	private String confirmaSenha;
	@Autowired
	private AuthenticationFacade authenticationFacade;
	@Autowired
	private UsuarioService usuarioService;
	@Autowired
	private FacesMessageUtils facesMessageUtils;

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getConfirmaSenha() {
		return confirmaSenha;
	}

	public void setConfirmaSenha(String confirmaSenha) {
		this.confirmaSenha = confirmaSenha;
	}

	@PostConstruct
	public void init() {
		usuario = new Usuario();
		buscaUsuario();
	}

	public void buscaUsuario() {
		usuario = usuarioService.findByLogin(authenticationFacade.getAuthentication().getName());
	}

	public void salvarNovaSenha() {

		BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

		if (confirmaSenha.equals(senha)) {

			usuario.setSenha(passwordEncoder.encode(senha));
			usuarioService.save(usuario);
			facesMessageUtils.addWarningMessage("Nova senha salva com sucesso!");

		}else {
			facesMessageUtils.addWarningMessage("As senhas digitadas não são iguais!");

		}
		senha = "";
		confirmaSenha = "";
	}

}

src/main/webapp/pessoas.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="/templates/default/main.xhtml">
	<ui:define name="content">
		<div class="row">
			<div class="col-md-12">
				<div class="card" style="margin-top: 20px">
					<div class="card-header ">
						<h4 class="card-title">Administração</h4>
						<h6 class="card-subtitle mb-2 text-muted">Pessoas</h6>
					</div>
					<h:form id="form-pessoas">
						<div class="card-body bg-light">
							<div class="row">
								<div class="col-md-12">
									<div class="table-responsive">
										<h:dataTable binding="#{table}"
											value="#{pessoaBean.pessoasList}" var="p"
											styleClass="table dataTable-pessoa table-striped table-sm">
											<h:column>
												<f:facet name="header">#</f:facet>
                                       		 	#{table.rowIndex + 1}
                                    		</h:column>

											<h:column>
												<f:facet name="header">Nome</f:facet>
                                       			 #{p.nome}
                                    		</h:column>

											<h:column>
												<f:facet name="header">CPF</f:facet>
												<h:outputLabel style="cpf" value="#{p.cpf}" />
		                                    </h:column>

											<h:column>
												<f:facet name="header">Data de Nascimento</f:facet>
												<h:outputLabel value=" #{p.dataNascimentoFormatado}">
												</h:outputLabel>
		
											</h:column>

											<h:column pt:style="text-align:center;padding:5px 0;">
												<f:facet name="header">
													<i class="fa fa-cog" aria-hidden="true"></i>
												</f:facet>
												<h:commandLink action="#{pessoaBean.prepareUpdate(p)}"
													style="text-decoration:none;" pt:data-toggle="modal"
													pt:data-target=".modal-cadastro" pt:data-backdrop="static"
													pt:data-keyboard="false">
													<i class="fa fa-pencil fa-fw" aria-hidden="true" />
													<f:ajax render="form-cadastro-pessoa" />
												</h:commandLink>
											</h:column>
										</h:dataTable>
									</div>
								</div>
							</div>
						</div>
						<div class="card-footer">
							<div class="btn-group" role="group">
								<h:commandLink styleClass="btn btn-success"
									pt:data-toggle="modal" pt:data-target=".modal-cadastro"
									pt:data-backdrop="static" pt:data-keyboard="false">
									<i class="fa fa-clone fa-fw" aria-hidden="true" /> Adicionar
                                        <f:ajax
										render="form-cadastro-pessoa"
										listener="#{pessoaBean.prepareSave}" />
								</h:commandLink>
							</div>
						</div>
					</h:form>
				</div>
			</div>
		</div>

		<!-- 		Modal Cadastrar pessoas-->
		<div class="modal modal-cadastro modal-draggable fade" tabindex="-1"
			role="dialog">
			<div class="modal-dialog modal-lg" role="document">
				<div class="modal-content">
				<h:form id="form-cadastro-pessoa">
					<h:messages />
					<div class="modal-header">
						<h:outputLabel rendered="#{pessoaBean.pessoa.id eq null}" styleClass="modal-title"
							value="Cadastro de Pessoas" />
						<h:outputLabel rendered="#{pessoaBean.pessoa.id ne null}" styleClass="modal-title" 
							value="Editar Dados" />

						<button type="button" class="close" data-dismiss="modal"
							aria-label="Close">
							<span aria-hidden="true">&#215;</span>
						</button>
					</div>
					
						<div class="modal-body bg-light">
							<div class="form-group row">
								<div class="col-md-12">
									<label for="nome">Nome</label>
									<h:inputText styleClass="form-control" required="true"
										requiredMessage="Campo nome é Obrigatorio"
										value="#{pessoaBean.pessoa.nome}">
									</h:inputText>

								</div>
								<div class="col-md-5">
									<label for="cpf">CPF</label>
									<h:inputText styleClass="form-control cpf" required="true"
										requiredMessage="Campo CPF é Obrigatorio"
										value="#{pessoaBean.pessoa.cpf}">
									</h:inputText>
								</div>
								<div class="col-md-7">
									<label for="email">Email</label>
									<h:inputText styleClass="form-control" required="true"
										requiredMessage="Campo Email é Obrigatorio"
										value="#{pessoaBean.pessoa.email}">
									</h:inputText>
								</div>
								<div class="col-md-4">
									<label>Data da Nascimento</label>
									<h:inputText pt:type="date" styleClass="form-control"
										value="#{pessoaBean.dataNascimento}" />
								</div>
								<div class="col-md-4">
									<label for="contato1">Contato 1</label>
									<h:inputText styleClass="form-control phone" required="true"
										requiredMessage="Campo Contato  é Obrigatorio"
										value="#{pessoaBean.pessoa.contato1}">
									</h:inputText>
								</div>

								<div class="col-md-4">
									<label for="contato2">Contato 2</label>
									<h:inputText styleClass="form-control phone"
										value="#{pessoaBean.pessoa.contato2}">
									</h:inputText>
								</div>

							</div>

							<hr />

							<div class="form-group row" id="divEndereco">
								<div class="col-md-12 mb-2">
									<label>ENDEREÇO</label>
								</div>
								<div class="col-md-3">
									<label>CEP</label>
									<h:inputText id="inptCep" styleClass="form-control cep"
										required="true" requiredMessage="Campo Email é Obrigatorio"
										value="#{pessoaBean.cepDigitado}">
										<f:ajax event="change" execute="@this"
											render="inptLogradouro inptBairro inptCidade inptUf"
											listener="#{pessoaBean.buscaCep}" />
									</h:inputText>
								</div>
								<div class="col-md-9">
									<label>Logradouro</label>
									<h:inputText disabled="true" id="inptLogradouro"
										styleClass="form-control"
										value="#{pessoaBean.pessoa.logradouro}">
									</h:inputText>
								</div>
								<div class="col-md-2">
									<label>Numero</label>
									<h:inputText styleClass="form-control" required="true"
										requiredMessage="Campo Email é Obrigatorio"
										value="#{pessoaBean.pessoa.numero}">
									</h:inputText>
								</div>
								<div class="col-md-4">
									<label>Complemento</label>
									<h:inputText styleClass="form-control"
										value="#{pessoaBean.pessoa.complemento}">
									</h:inputText>
								</div>

								<div class="col-md-6">
									<label>Bairro</label>
									<h:inputText id="inptBairro" disabled="true"
										styleClass="form-control"
										value="#{pessoaBean.pessoa.bairro}">
									</h:inputText>
								</div>

								<div class="col-md-6">
									<label>Cidade</label>
									<h:inputText id="inptCidade" disabled="true"
										styleClass="form-control"
										value="#{pessoaBean.pessoa.cidade}">
									</h:inputText>
								</div>

								<div class="col-md-2">
									<label>Estado(UF)</label>
									<h:inputText id="inptUf" disabled="true"
										styleClass="form-control"
										value="#{pessoaBean.pessoa.uf}">
									</h:inputText>
								</div>
							</div>
						</div>

						<div class="modal-footer">

							<h:commandLink style="margin-right:5px"
								styleClass="btn btn-success" pt:data-dismiss="modal">
								<i class="fa fa-save fa-fw" aria-hidden="true" />

								<f:ajax event="click" execute="@form"
									render="@form :form-pessoas" listener="#{pessoaBean.save}"
									onevent="dataTablePessoaFromJSF" /> Salvar

                            </h:commandLink>

							<h:commandLink style="margin-right:5px"
								styleClass="btn btn-danger" pt:data-dismiss="modal">
								<i class="fa fa-sign-out fa-fw" aria-hidden="true" /> Fechar
                                <f:ajax />
							</h:commandLink>

						</div>
					</h:form>

				</div>
			</div>
		</div>
		<!-- Fecha Modal adicionar-->

	</ui:define>
</ui:composition>